# Generated by Django 3.2.4 on 2021-06-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210619_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='lineas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.lineas'),
        ),
    ]
