# Generated by Django 3.2.4 on 2021-06-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_recorrido_lineas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lineas',
            new_name='Linea',
        ),
    ]
