# Generated by Django 3.2.4 on 2021-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_lineas_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='lineas',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='lineas',
            field=models.ManyToManyField(blank=True, null=True, to='App.Linea'),
        ),
    ]
