# Generated by Django 3.2.4 on 2021-06-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210619_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='lineas',
            field=models.ManyToManyField(blank=True, to='App.Linea'),
        ),
    ]
