# Generated by Django 3.2.4 on 2021-06-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_recorrido_lineas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(max_length=5000)),
                ('problema', models.TextField(max_length=5000)),
                ('solución', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='destino',
            name='destino',
            field=models.CharField(choices=[('Plaza de armas', 'Plaza de armas'), ('Escuela Militar', 'Escuela Militar')], max_length=150),
        ),
    ]
