# Generated by Django 3.2.4 on 2021-06-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210622_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='solución',
            new_name='solucion',
        ),
    ]
